### ISSUE TITLE
As a SO, I want to be able to link webforms to ServiceNow

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/cu_forms_bundle#43]
@kreynen commented on [Thu Jun 01 2017](https://github.com/CuBoulder/express/issues/1115)

## Context

---

@jwfuller commented on [Tue Jun 20 2017](https://github.com/CuBoulder/express/issues/1115#issuecomment-309876173)

Need to make sure we can handle situations where they cannot accept data

---

@owenmorrill commented on [Mon Sep 17 2018](https://github.com/CuBoulder/express/issues/1115#issuecomment-422084350)

Add ServiceNow API integration similar to what's used on https://oit.colorado.edu
- [ ] process a webform email so that the sent email has the uploaded file as an email attachment?

**Comment by owenmorrill** [comment]
Alright, about ServiceNow. We have to make it a configuration option during the webform build process as to whether or not to connect it to ServiceNow. Maybe we could collect authorization info then? 

We can’t just pick and choose fields to send over. Maybe we need to take static info about the form itself and send that as the unique fields and then lump everything else together as a single value to send over as the body?

Either that, or we need something of a wizard setup, “You need a ‘title’ field. Now you need a ‘short description’ field…”

Or, we grant each field a checkbox where you pick a ServiceNow field to map to?

ServiceNow REST API for creating incidents is pretty slick—JS or cURL: https://docs.servicenow.com/bundle/geneva-servicenow-platform/page/integrate/inbound_rest/task/t_GetStartedCreateInt.html

ServiceNow dev instance: https://dev21034.service-now.com/nav_to.do?uri=%2F$restapi.do

*notes for Monday

**Comment by owenmorrill** [comment]
Not sure how to configure authentication to test the personal dev site I've setup. It looks like the IT code has the authentication in another part of the code and in variables. Might ask about it tomorrow, but I'm stuck either way with the sn dev instance.

**Comment by owenmorrill** [comment]
https://www.youtube.com/watch?v=ALJ3_OPnR28
